[package]
name = "rs-es"
version = "0.10.0"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[dependencies]
hyper = "0.11"
reqwest = "0.8.5"
log = "^0.3"
maplit = "^0.1"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
url = "^1.2"

[dev-dependencies]
env_logger = "^0.4"
regex = "^0.2"
